module.exports = {
  SKILLS: [
    { name: 'ReactJS', image: '/tech/react.svg' },
    { name: 'Anuglar', image: '/tech/angular.svg' },
    { name: 'VueJS', image: '/tech/vuejs.svg' },
    { name: 'NodeJS', image: '/tech/nodejs.svg' },
    { name: 'Ruby on Rails', image: '/tech/rails.svg' },
    { name: 'Sinatra', image: '/tech/sinatra.svg' },
    { name: 'Phoenix', image: '/tech/phoenix.svg' },
    { name: 'Elixir', image: '/tech/elixir.svg' },
    { name: 'GraphQL', image: '/tech/graphql.svg' },
    { name: 'mongoDB', image: '/tech/mongodb.svg' },
    { name: 'mySQL', image: '/tech/mysql.svg' },
    { name: 'postgreSQL', image: '/tech/postgresql.svg' },
    { name: 'Redis', image: '/tech/redis.svg' },
    { name: 'AWS', image: '/tech/aws.svg' },
    { name: 'GCP', image: '/tech/gcp.svg' },
    { name: 'Ansible', image: '/tech/ansible.svg' },
    { name: 'Github', image: '/tech/github.svg' },
    { name: 'Nginx', image: '/tech/nginx.svg' },
  ],
  PROJECTS: {
    JollyHQ: {
      slug: 'jollyhq',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/JollyHQ.png',
      siteUrl: 'https://www.jollyhq.com/',
      stack: [
        'ReactJS',
        'Ruby on Rails',
        'Node.js',
        'Express',
        'MongoDB',
        'Mocha',
        'Jest',
        'Redis',
        'AWS S3',
        'AWS EC2',
        'AWS Kinesis',
        'Segment',
        'Material UI',
        'Ghost CMS',
        'GatsbyJS',
        'Github Actions',
        'Nginx',
      ],
    },
    Awato: {
      slug: 'awato',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Awato.png',
      siteUrl: 'https://awato.co/',
      stack: [
        'AngularJS',
        'Hanami',
        'PostgresQL',
        'Docker',
        'Ruby on Rails',
        'AWS S3',
        'AWS SES',
        'AWS SQS',
        'Redis',
        'Bootstrap 3',
        'Circle CI',
        'Rspec',
        'Heroku',
      ],
    },
    Glorii: {
      slug: 'glorii',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Glorii.png',
      siteUrl: 'https://glorii.co/',
      stack: [
        'Ruby on Rails',
        'StimulusJS',
        'MySQL',
        'AWS EC2',
        'AWS SES',
        'AWS S3',
        'Wordpress',
        'Rspec',
        'Linode',
        'Bootstrap 5',
        'Capistrano',
        'Ansible',
        'Nginx',
      ],
    },
    RVAHappyHours: {
      slug: 'rva-happy-hours',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/RVAHappyHours.png',
      siteUrl: 'https://www.rvahappyhours.com/',
      stack: [
        'Elixir',
        'Phoenix',
        'Ecto MySQL',
        'Distillery',
        'AWS S3',
        'Gigalixir',
        'Bootstrap 4',
        'jQuery',
        'ExMock',
      ],
    },
    InstantAutographs: {
      slug: 'instant-autographs',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/InstantAutographs.png',
      siteUrl: 'https://www.instantautographs.com/',
      stack: ['Ruby on Rails', 'PostgreSQL', 'Bootstrap 4', 'AWS S3', 'AWS SES', 'Heroku', 'RSpec'],
    },
    Rishaba: {
      slug: 'rishaba',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Rishaba.png',
      siteUrl: 'https://rishaba.in',
      stack: [
        'ReactJS',
        'GatsbyJS',
        'GraphQL',
        'formSpree',
        'Netlify',
        'AWS S3',
        'AWS CloudFront',
        'AWS Route 53',
        'AWS Certificate Manager',
      ],
    },
    Roameo: {
      slug: 'roameo',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Roameo.png',
      siteUrl: 'https://roameo.club/',
      stack: [
        'Ruby on Rails',
        'React Native',
        'Expo',
        'AWS S3',
        'AWS SES',
        'Bootstrap',
        'Nginx',
        'Linode',
        'Capistrano',
        'RSpec',
        'Selenium',
      ],
    },
    ScanTheMarket: {
      slug: 'scan-the-market',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/ScanTheMarket.png',
      siteUrl: 'https://scanthemarket.in',
      stack: [
        'Elixir',
        'Phoenix/Liveview',
        'postgreSQL',
        'Linode',
        'ExMock',
        'Nginx',
        'Ansible',
        'Github Actions',
        'Distillery',
      ],
    },
    StateEnergyCalculator: {
      slug: 'Maharastra State Energy Calculator',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/energyCalculator.png',
      siteUrl: 'https://calculator.mahadiscom.in/',
      stack: ['Sinatra', 'Bootstrap', 'Nginx', 'Linode'],
    },
    Beamdock: {
      slug: 'beamdock',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Beamdock.png',
      siteUrl: 'https://beamdock.com',
      stack: ['Ruby on Rails', 'StimulusJS', 'AWS S3', 'AWS SES', 'Linode', 'MySql', 'Nginx', 'Lua', 'Openresty'],
    },
    Acuments: {
      slug: 'acuments',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/Acuments.png',
      siteUrl: '',
      stack: ['Ruby', 'Middleman', 'Bootstrap', 'Nginx', 'Tech Blog'],
    },
    CommitLive: {
      slug: 'commit-live',
      description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
      image: '/projects/CommitLive.png',
      siteUrl: 'https://commit.live',
      stack: ['Ruby on Rails', 'RSpec', 'Bootstrap', 'Heroku', 'EC2', 'Capistrano', 'postgreSQL'],
    },
  },
};
